main: bonn2.reinforcedTurtleHelmets.Main
name: ReinforcedTurtleHelmets
version: 1.3
author: bonn2
api-version: 1.16
softdepend:
  - ArmorEquipEvent
commands:
  rth:
    description: Main command for Reinforced Turtle Helmets
